name: "Nix Build and Test"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  fast-checks:
    name: Fast Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Run Fast Checks
        run: |
          nix build -L \
            .#checks.x86_64-linux.lint-deadnix \
            .#checks.x86_64-linux.lint-statix \
            .#checks.x86_64-linux.lint-formatting \
            .#checks.x86_64-linux.lint-shebang \
            .#checks.x86_64-linux.lint-shellcheck \
            .#checks.x86_64-linux.lint-machete \
            .#checks.x86_64-linux.lint-clippy

  checks:
    name: Check ${{ matrix.check }}
    needs: fast-checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - py-tests
          - rs-client-tests
          - rs-unit
          - rs-bwrap
          - rs-gc
          - rs-integration
          - rs-containers
          - rs-executor
          - lib-integration
          - lib-invalidation
          - lib-pipeline-logic
          - lib-dynamic-params-validation
          - lib-parameters
          - lib-parameters-types
          - e2e-local-bwrap-pure
          - e2e-local-bwrap-impure
          - e2e-local-bwrap-mount-paths
          - e2e-local-docker-pure
          - e2e-local-docker-impure
          - e2e-local-docker-mount-paths
          - e2e-local-podman-pure
          - e2e-local-podman-impure
          - e2e-local-podman-mount-paths
          - e2e-local-bwrap-node-local-path
          - e2e-remote-bwrap-pure
          - e2e-remote-bwrap-impure
          - e2e-remote-bwrap-mount-paths
          - e2e-remote-docker-pure
          - e2e-remote-docker-impure
          - e2e-remote-docker-mount-paths
          - e2e-remote-podman-pure
          - e2e-remote-podman-impure
          - e2e-remote-podman-mount-paths
          - e2e-remote-slurm
          - non-nixos-local-bwrap-impure
          - non-nixos-remote-bwrap-pure
          - non-nixos-remote-bwrap-impure
          - non-nixos-remote-bwrap-mount-paths
          - static-analysis
          - lib-deps-fail-missing
          - lib-deps-pass-complex
          - lib-deps-pass-valid
          - e2e-incremental-sync
          - lib-large-lab
          - lib-buildcommand-size
          - lib-stage-env-size
          - lib-resource-hints
          - lib-zip-params
          - lib-non-scalar-params
          - lib-repx-examples
          - e2e-bwrap-overlay-fallback
          - e2e-gc-local
          - e2e-gc-remote
          - e2e-scatter-gather-cancel
          - e2e-init
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Run E2E Check
        run: nix build -L .#checks.x86_64-linux.${{ matrix.check }}

