name: "PR Check"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  fast-checks:
    name: Fast Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Run Fast Checks
        run: |
          nix build -L \
            .#checks.x86_64-linux.lint-deadnix \
            .#checks.x86_64-linux.lint-statix \
            .#checks.x86_64-linux.lint-formatting \
            .#checks.x86_64-linux.lint-shebang \
            .#checks.x86_64-linux.lint-shellcheck \
            .#checks.x86_64-linux.lint-machete \
            .#checks.x86_64-linux.lint-clippy
